title: Khai Tran # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Psst! I love data analytics and I'm a proud data nerd.
  <br><br>
  Oh, and I'm also obsessed with Salesforce. 
  <br><br>
  <a href="https://www.linkedin.com/in/khai-tran-3a5076226/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
